# Copyright (c) 2026 Antmicro <www.antmicro.com>
# SPDX-License-Identifier: Apache-2.0

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path
from re import compile
from re import escape as escape_regex

from topwrap.interconnects.axi import AXIInterconnect
from topwrap.interconnects.wishbone_rr import WishboneInterconnect
from topwrap.model.connections import (
    Connection,
    ConstantConnection,
    InterfaceConnection,
    ReferencedInterface,
)
from topwrap.model.design import Design, ModuleInstance
from topwrap.model.interconnect import (
    Interconnect,
    InterconnectManagerParams,
    InterconnectSubordinateParams,
)
from topwrap.model.misc import Identifier, ObjectId, VariableName
from topwrap.plugin.base import BasePlugin, BuildContext
from typing_extensions import Any, Callable, Iterable, Union, cast

logger = logging.getLogger(__name__)

RENODE_GUEST_PAGE_SIZE = 0x1000

REPL_PREAMBLE = f"""
// This file has been automatically generated by {Path(__file__).name}"""


class RenodeValue(ABC):
    @abstractmethod
    def display(self) -> str: ...


def get_pretty_bytes(i: int) -> int:
    if i < 0:
        logging.error(f"invalid input: {i}")
        exit(1)

    exp = 1
    while 2 ** (8 * exp) <= i:
        exp += 1

    return exp


def render_hex(i: int, bytes: int) -> str:
    return "0x" + i.to_bytes(bytes, byteorder="big").hex()


class RenodeValueInt(RenodeValue):
    def __init__(self, i: int, is_hex: bool = False):
        self.i = i
        self.is_hex = is_hex

    def display(self) -> str:
        if self.is_hex:
            return render_hex(self.i, get_pretty_bytes(self.i))
        return str(self.i)


def find_by_io_con(target_name: str, interface_name: str) -> Callable[[Connection], bool]:
    def _wrapped(con: Connection) -> bool:
        return (
            con.target.io.name == interface_name
            and con.target.instance is not None
            and con.target.instance.name == target_name
        )

    return _wrapped


@dataclass
class RenodeMemoryMap:
    offset: int
    extent: int | None

    def get_aligned_size(self, alignment: int) -> int | None:
        if self.extent is None:
            return None
        return (
            self.extent
            if self.extent % alignment == 0
            else self.extent + (alignment - self.extent % alignment)
        )


@dataclass
class RenodeDevice:
    name: str
    device_name: str
    memory_map: RenodeMemoryMap | None
    fields: dict[str, RenodeValue]

    def _render_head(self) -> str:
        row: list[str] = []

        row.append(f"{self.name}: {self.device_name} @ sysbus")

        if self.memory_map:
            addr = render_hex(self.memory_map.offset, get_pretty_bytes(self.memory_map.offset))
            aligned_size = self.memory_map.get_aligned_size(RENODE_GUEST_PAGE_SIZE)
            if aligned_size:
                # align to guest page 0x1000
                size = render_hex(aligned_size, get_pretty_bytes(aligned_size))
                row.append(f" <{addr}, +{size}>")
            else:
                row.append(f" {addr}")
        return "".join(row)

    def _render_fields(self) -> list[str]:
        rows: list[str] = []

        for key, val in self.fields.items():
            rows.append(f"{key}: {val.display()}")

        return rows

    def render(self) -> str:
        lines: list[str] = []

        lines.append(self._render_head())
        lines.extend(4 * " " + field for field in self._render_fields())

        return "\n".join(lines)


class FieldResolver(ABC):
    dest: VariableName
    symbol: VariableName

    def __init__(self, dest: str, symbol: str):
        self.dest = dest
        self.symbol = symbol

    @abstractmethod
    def get_parameter(
        self, instance: ModuleInstance, mm: RenodeMemoryMap | None
    ) -> tuple[str, RenodeValue]: ...

    @staticmethod
    def parse(dest: str, src: str) -> "FieldResolver":
        m = _QUERY_RE.fullmatch(src)
        if not m:
            logger.error("Failed to compile regular expression for query")
            exit(1)

        property_source = m["source"]
        property_symbol = m["symbol"]

        return _SOURCE_MAP[property_source](dest, property_symbol)


class ResolveMemoryMapProperty(FieldResolver):
    def get_parameter(
        self, instance: ModuleInstance, mm: RenodeMemoryMap | None
    ) -> tuple[str, RenodeValue]:
        if not mm:
            logger.error("Tried to resolve a memory-map property for non-existent memory-map")
            exit(1)

        if self.symbol == "size":
            memory_size = mm.get_aligned_size(RENODE_GUEST_PAGE_SIZE)
            if not memory_size:
                logger.error("Size does not exist for memory map")
                exit(1)

            return self.dest, RenodeValueInt(memory_size, True)

        if self.symbol == "address":
            address = mm.offset
            return self.dest, RenodeValueInt(address, True)

        logger.error(f"The following memory map property is not supported: {self.symbol}")
        exit(1)


class ResolveConnectionspProperty(FieldResolver):
    def get_parameter(
        self, instance: ModuleInstance, mm: RenodeMemoryMap | None
    ) -> tuple[str, RenodeValue]:
        design = instance.parent
        con = design.connections.find_by(find_by_io_con(instance.name, self.symbol))

        if con is None:
            logging.error(f"connection property {self.symbol} not found")
            exit(1)

        if not isinstance(con, ConstantConnection):
            logging.error(f"only static connections are supported: {self.symbol}")
            exit(1)

        value = con.source.elaborate()
        if value is None:
            logging.error(f"therese no source to the following connection {self.symbol}")
            exit(1)

        return self.dest, RenodeValueInt(value, False)


_SOURCE_MAP = {
    "memory_map": ResolveMemoryMapProperty,
    "connections": ResolveConnectionspProperty,
}
_QUERY_RE = compile(
    r"^\.(?P<source>" + "|".join(map(escape_regex, _SOURCE_MAP.keys())) + r")\.(?P<symbol>\b\w+\b)$"
)


class RenodeDeviceFieldResolve:
    def __init__(self, mod_id: Identifier, dev: str):
        super().__init__()
        self.mod_id = mod_id
        self.dev = dev
        self.resolvers: list[FieldResolver] = []

    def add_resolver(self, resolver: FieldResolver):
        self.resolvers.append(resolver)

    def get_module_id(self) -> Identifier:
        return self.mod_id

    def get_renode_device(self) -> str:
        return self.dev

    def get_parameters(
        self, instance: ModuleInstance, mm: RenodeMemoryMap | None
    ) -> dict[str, RenodeValue]:
        fields = {}
        for resolver in self.resolvers:
            key, val = resolver.get_parameter(instance, mm)
            if key in fields:
                logging.error(f"two mappings target the same dest: {key}")
                exit(1)
            fields[key] = val
        return fields


@dataclass
class RenodeMapping:
    mapping: dict[VariableName, tuple[ModuleInstance, RenodeDeviceFieldResolve]]

    @staticmethod
    def create_mapping(
        resolvers: list[RenodeDeviceFieldResolve], design: Design
    ) -> "RenodeMapping":
        resolver_lookup = {r.get_module_id(): r for r in resolvers}
        mapping = RenodeMapping({})

        for instance in design.components:
            mod_id = instance.module.id
            resolver = resolver_lookup.get(mod_id, None)

            if resolver is None:
                continue

            mapping.mapping[instance.name] = (instance, resolver)
            logging.info(f"Assigning Renode peripheal {resolver.dev} to {instance.name}")

        return mapping

    def __contains__(self, element: VariableName) -> bool:
        return element in self.mapping

    def items(
        self,
    ) -> Iterable[tuple[str, tuple[ModuleInstance, RenodeDeviceFieldResolve]]]:
        return self.mapping.items()


class InterconnectionWrapper:
    intercon: Union["AXIInterconnect", "WishboneInterconnect"]

    def __init__(self, intercon: Interconnect):
        if not (
            isinstance(intercon, AXIInterconnect) or isinstance(intercon, WishboneInterconnect)
        ):
            logging.error("only axi/wishbone interconnects are supported")
            exit(1)
        self.intercon = intercon

    def get_managers(
        self,
    ) -> Iterable[tuple[ObjectId[ReferencedInterface], InterconnectManagerParams]]:
        return self.intercon.managers.items()

    def get_subordinates(
        self,
    ) -> Iterable[tuple[ObjectId[ReferencedInterface], InterconnectSubordinateParams]]:
        return self.intercon.subordinates.items()


def _get_mmap_managers(
    intercon: InterconnectionWrapper, mapping: RenodeMapping
) -> list[VariableName]:
    # Resolve managers first, assuming interfaces can be grouped
    unique_manager_instances: set[VariableName] = set()
    for _interface, _ in intercon.get_managers():
        interface = _interface.resolve()
        instance = interface.instance

        if not instance:
            logging.error("A manager needs an instantiated interface")
            exit(1)

        unique_manager_instances.add(instance.name)

    for manager in unique_manager_instances:
        if manager not in mapping:
            logging.error("A manager has to be mapped to a Renode peripheral")
            exit(1)

    return list(unique_manager_instances)


def _get_subordinate_mmap(
    intercon: InterconnectionWrapper,
) -> list[tuple[ReferencedInterface, RenodeMemoryMap]]:
    # Resolve subordinates by walking interface connections, inheriting the
    # top-level memory map
    unresolved_stack: list[tuple[ReferencedInterface, RenodeMemoryMap]] = []
    for obid, sub in intercon.get_subordinates():
        sub_int = obid.resolve()

        sub_inst = sub_int.instance
        if not sub_inst:
            logging.error("A subordinate needs to be an instance")
            exit(1)

        addr = sub.address.elaborate()
        if addr is None:
            logging.error(f"Subordinate {sub_inst.name} needs an address")
            exit(1)

        size = sub.size.elaborate()
        if size is None:
            logging.error(f"Subordinate {sub_inst.name} needs a size")
            exit(1)

        rmm = RenodeMemoryMap(addr, size)

        unresolved_stack.append((sub_int, rmm))

    return unresolved_stack


def resolve_memorymap(
    design: Design, mapping: RenodeMapping
) -> dict[VariableName, RenodeMemoryMap | None]:
    intercon = list(design.interconnects)

    if len(intercon) == 0:
        logging.error("Design is missing an interconnection network")
        exit(1)

    if len(intercon) > 1:
        logging.error("Multiple interconnection networks are not supported")
        exit(1)
    intercon = InterconnectionWrapper(intercon[0])

    mm: dict[VariableName, RenodeMemoryMap | None] = {}

    for manager in _get_mmap_managers(intercon, mapping):
        mm[manager] = None

    unresolved_stack = _get_subordinate_mmap(intercon)

    def is_outgoing_connection(name: str) -> Callable[[Connection], bool]:
        def _wrapper(con: Connection) -> bool:
            src = con.source
            if not isinstance(src, ReferencedInterface):
                return False

            if not src.instance:
                logging.error("The the source of a interface needs to be an instance")
                exit(1)

            return name == src.instance.name

        return _wrapper

    while unresolved_stack:
        interface, rmm = unresolved_stack.pop()
        if not interface.instance:
            logging.error("Interfaces needs to be instantiated")
            exit(1)

        if interface.instance.name in mapping:
            mm[interface.instance.name] = rmm
            continue

        edge = design.connections.find_by(is_outgoing_connection(interface.instance.name))
        if edge is None:
            logging.error(
                f"{interface.instance.name} is a leaf, but is missing a mapped Renode device"
            )
            exit(1)

        if not isinstance(edge, InterfaceConnection):
            logging.error("is_outgoing_connection is buggy")
            exit(1)

        unresolved_stack.append((edge.target, rmm))

    return mm


def create_resolvers(mod: Design) -> list[RenodeDeviceFieldResolve]:
    metadata = mod.extensions.find_by_name_or_error("renode_peripheral_gen")

    data = metadata.data

    if not isinstance(data, dict):
        logging.error("renode_peripheral_gen has to be a dictionary")
        exit(1)
    if "supported_peripherals" not in data:
        return []

    supported_peripherals = cast(dict[str, Any], data)["supported_peripherals"]
    if not isinstance(supported_peripherals, list):
        logging.error("supported_peripherals has to be a list")
        exit(1)

    resolvers = []

    for peripheral in supported_peripherals:
        if not isinstance(peripheral, dict):
            logging.error("renode_peripheral_gen.supported_peripherals[*] has to be a dictionary")
            exit(1)
        peripheral = cast(dict[str, Any], peripheral)

        target = peripheral["target"]
        if not isinstance(target, dict):
            logging.error(
                "renode_peripheral_gen.supported_peripherals[*].target has to be a dictionary"
            )
            exit(1)
        target = cast(dict[str, str], target)

        if "name" not in target:
            logging.error("renode_peripheral_gen.supported_peripherals[*].target.name has to exist")
            exit(1)

        expected_keys = set(["name", "vendor", "library", "version"])
        keys = set(target.keys())
        if not keys <= expected_keys:
            unknown_keys = keys - expected_keys
            logging.error(
                "renode_peripheral_gen.supported_peripherals[*].target: "
                f"unknown keys {', '.join(unknown_keys)}"
            )
            exit(1)

        if not all(isinstance(s, str) for s in target.values()):
            logging.error(
                "renode_peripheral_gen.supported_peripherals[*].target: all values must be strings"
            )
            exit(1)

        ident = Identifier(**target)
        renode_device = peripheral["renode_device"]

        device_resolver = RenodeDeviceFieldResolve(ident, renode_device)

        if "map" not in peripheral:
            resolvers.append(device_resolver)
            continue

        field_map = peripheral["map"]
        if not isinstance(field_map, list):
            logging.error("renode_peripheral_gen.supported_peripherals[*].map has to be a list")
            exit(1)

        for field_resolver in field_map:
            if not isinstance(field_resolver, dict):
                logging.error(
                    "renode_peripheral_gen.supported_peripherals[*].map[*] has to be a dictionary"
                )
                exit(1)
            field_resolver = cast(dict[str, str], field_resolver)
            dest = field_resolver["dest"]
            src = field_resolver["src"]
            device_resolver.add_resolver(FieldResolver.parse(dest, src))

        resolvers.append(device_resolver)
    return resolvers


@dataclass
class FilterRule:
    allow: bool
    pattern: str | None

    def check(self, target: str) -> bool | None:
        if self.pattern is None:
            return True

        matches = self.pattern == target

        if not matches:
            return None

        return self.allow

    @staticmethod
    def parse_pattern(pattern: str) -> "FilterRule":
        if pattern == "*":
            return FilterRule(True, None)

        if "*" in pattern:
            logging.error(f"partial wildcards are not supported: {pattern}")
            exit(1)

        allow = not pattern.startswith("-")

        return FilterRule(allow, pattern.removeprefix("-"))


@dataclass
class DeviceFilter:
    rules: list[FilterRule]

    def check(self, target: str) -> bool:
        status = None
        for rule in self.rules:
            new_status = rule.check(target)

            if new_status is None:
                continue

            status = new_status

        # If no rules match the target, it's implicitly filtered out
        return status is not None and status


@dataclass
class OutputMap:
    filename: str
    device_filter: DeviceFilter | None
    includes: list[str]


def parse_output_maps(des: Design) -> list[OutputMap]:
    metadata = des.extensions.find_by_name_or_error("renode_peripheral_gen")

    data = metadata.data

    if not isinstance(data, dict):
        logging.error("renode_peripheral_gen has to be a dict")
        exit(1)
    if "output" not in data:
        return []

    data = cast(dict[str, Any], data)
    outputs = data["output"]

    if not isinstance(outputs, list):
        logging.error("renode_peripheral_gen.output has to be a list")
        exit(1)

    output_maps: list[OutputMap] = []

    for output in outputs:
        if not isinstance(output, dict):
            logging.error("renode_peripheral_gen.output[*] has to be a dict")
            exit(1)
        output = cast(dict[str, Any], output)

        if "filename" not in output:
            logging.error("filename has to exist")
            exit(1)

        filename = output["filename"]
        if not isinstance(filename, str):
            logging.error("renode_peripheral_gen.output[*].filename has to be a string")
            exit(1)

        device_filter = None
        if "filter" in output:
            filter_rules = output["filter"]
            if not (
                isinstance(filter_rules, list)
                and all(isinstance(rule, str) for rule in filter_rules)
            ):
                logging.error("renode_peripheral_gen.output[*].filter has to be a list of strings")
                exit(1)
            filter_rules = cast(list[str], filter_rules)

            device_filter = DeviceFilter(list(map(FilterRule.parse_pattern, filter_rules)))

        includes = []
        if "includes" in output:
            includes = output["includes"]
            if not (isinstance(includes, list) and all(isinstance(inc, str) for inc in includes)):
                logging.error(
                    "renode_peripheral_gen.output[*].includes has to be a list of strings"
                )
                exit(1)
        includes = cast(list[str], includes)

        output_maps.append(OutputMap(filename, device_filter, includes))

    return output_maps


@dataclass
class RenodePlatform:
    devices: list[RenodeDevice]

    @staticmethod
    def define(
        renode_mapping: RenodeMapping,
        memory_map: dict[VariableName, RenodeMemoryMap | None],
    ) -> "RenodePlatform":
        devices: list["RenodeDevice"] = []

        for name, (instance, resolver) in renode_mapping.items():
            mm = memory_map[name]
            devices.append(
                RenodeDevice(
                    name,
                    resolver.get_renode_device(),
                    mm,
                    resolver.get_parameters(instance, mm),
                )
            )

        return RenodePlatform(devices)

    def render_config(self, preamble: str, includes: list[str], filter: DeviceFilter | None) -> str:
        lines = []

        lines.append(preamble)
        lines.extend(f'using "{fname}"' for fname in includes)
        lines.extend(
            dev.render() for dev in self.devices if filter is None or filter.check(dev.name)
        )
        lines.append("")

        return "\n\n".join(lines)


class RenodePeripheralGen(BasePlugin):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.outputs: dict[str, str] = {}

    def post_transform(self, ctx: BuildContext):
        top_module = ctx.top_module
        if not top_module:
            logging.error("expected top module to exist")
            exit(1)

        if not top_module.design:
            logging.error("expected top-level design")
            exit(1)

        top_design = cast(Design, top_module.design)

        output_maps = parse_output_maps(top_design)

        resolvers = create_resolvers(top_design)

        renode_mapping = RenodeMapping.create_mapping(resolvers, top_design)

        memory_map = resolve_memorymap(top_design, renode_mapping)

        for i_name, mm in memory_map.items():
            if mm is None:
                logging.info(f"Resolved memory map for {i_name}: (,)")
            else:
                logging.info(
                    f"Resolved memory map for {i_name}: "
                    f"({render_hex(mm.offset, 4)}, {mm.get_aligned_size(RENODE_GUEST_PAGE_SIZE)})"
                )

        platform = RenodePlatform.define(renode_mapping, memory_map)

        if not output_maps:
            print(platform.render_config(REPL_PREAMBLE, [], None))

        for output in output_maps:
            src = platform.render_config(REPL_PREAMBLE, output.includes, output.device_filter)
            self.outputs[output.filename] = src

    def pre_output_writing(self, ctx: BuildContext, target_dir: Path):
        for filename, src in self.outputs.items():
            out_path = target_dir / filename
            if out_path.exists() and out_path.is_dir():
                logging.error("cannot write to a directory")
                exit(1)
            logging.info(f"writing REPL: {out_path}")
            out_path.write_text(src)
